// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using System.Diagnostics;

namespace Papercut.Macos
{
	public partial class ScriptViewController : NSViewController
	{
		public ScriptViewController (IntPtr handle) : base (handle)
		{
		}

	}
}
